export { default as LoginForm } from "./LoginForm";
export { default as SignupForm } from "./SignupForm";
export { default as ForgotPasswordForm } from "./ForgotPasswordForm";
export { default as OtpForm } from "./OtpForm";
export { default as EmailForm } from "./EmailForm";
export { default as PasswordForm } from "./PasswordForm";
export { default as DetailsForm } from "./DetailsForm";
export { default as SocialLoginForm } from "./SocialLoginForm";
export { default as ConfirmPasswordForm } from "./ConfirmPasswordForm";
